### PR TITLE
Isolate each test results by executing test in its own Global

### LINKED ISSUE #129: SixSpeed runner seems failed to isolate tests
It seems that performance of "six-speed-templatestring-es6" depends on the fact that the calling test function is inlined from the test harness. And it depends on how to run SixSpeed in the [test runner](https://github.com/mozilla/arewefastyet/blob/master/benchmarks/six-speed/test.js).

When running the "template_string.es5" which is executed at first in the above harness, it is inlined and the result is like [this](https://arewefastyet.com/#machine=29&view=single&suite=six-speed&subtest=templatestring-es5).

Second time, when running "testmplate_string.es6" in the same loop, JSC does not inline it. Then the performance is like [this](https://arewefastyet.com/#machine=29&view=single&suite=six-speed&subtest=templatestring-es6)

If we replace the order of "template_string.es6" and "template_string.es5", the result becomes swapped due to inlining which involves test harness's loop.

However, I don't think it is good. The measured time depends on the order of the benchmarks defined in the [harness](https://github.com/mozilla/arewefastyet/blob/master/benchmarks/six-speed/test.js#L12-L39).
And it depends on how harness writes the loop to measure the time of the benchmarks.
This means that the current test runner a bit fails to isolate tests each other.

What do you think of running the tests in more isolated manner to measure the performance of each features precisely? For example, invoking shells for each tests.
Note: In WebKit, I [annotate](https://github.com/WebKit/webkit/blob/master/PerformanceTests/SixSpeed/wrappers/wrapper.js#L9) the target function with `noInline` special JSC function to avoid inlining which involves test harness itself. And WebKit's `Tools/Scripts/run-jsc-benchmarks` invokes JSC shell for each test.

Finally, I would like to say big thanks to arewefastyet. It allows us to track performances in multiple shells. It is quite helpful to find regression!

### PR DESCRIPTION
**Pull request by Constellation**
This test harness effectively avoids involving the harness itself in inlining.
Currently, this patch does not prevent us from inlining test and iteration loop.
But making it requires some special function like `noInline()` in JSC shell.
Fix #129 issue.

### CODE REVIEW

**Comment by Constellation** [comment]
Current data in arewefastyet is typical one.
https://arewefastyet.com/#machine=29&view=single&suite=six-speed&subtest=templatestring-es6
JSC sometimes gets super fast, this is because inlining in test harness sometimes involves this function.

**Comment by Constellation** [comment]
Ping?

**Comment by bnjbvr** [comment]
@Constellation ping?

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.

**Pull request closed without merging**
