### PR TITLE
remove webglsamples/ benchmark as it is unused and contained a refere…

### PR DESCRIPTION
**Pull request by jmaher**
…nce to ejs package that had a security flaw

### CODE REVIEW

**Comment by jmaher** [comment]
@bnjbvr can you review this and merge it?

**Comment by bnjbvr** [comment]
Looks good to me, thanks!

**Comment by bnjbvr** [comment]
Just one thing before merging: can you please update the commit message to fix the `remote` vs `remove` typo in there? Thanks!

**Comment by jmaher** [comment]
updated the commit message, please merge and lets get this issue resolved, thanks @bnjbvr

**Comment by bnjbvr** [comment]
LGTM, thanks.

**Pull request merged**
