### PR TITLE
Fix width of top bar on Overview page

### PR DESCRIPTION
**Pull request by Timvde**
I promised to do this pull request 2 years ago or so, so let's finally do it :P
Is there any documentation about how to run the site locally to verify this fix?

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thanks for the PR! Since this is a scss file, I'd suppose there should be a build step or something that rebuilds the whole CSS.

@h4writer, can you have a look please? Also, is there a way to run the website locally so as to check the fix?

**Comment by h4writer** [comment]
Sure. My laptop just broke down i.e. it will be a short message, since I need to get everything working again. I hope it helps though.

I have been a bad actor here. It used to work with Sass (http://sass-lang.com/). But I don't know what the steps are to compile the sass to css anymore. Secondly I think I might have changed some rules directly in the css file. I.e. it would be best to regenerate the css file and afterwards look at the differences and get them back in the sass files. Sorry!

There are some installation instructions on https://github.com/mozilla/arewefastyet/wiki/Installation. Though not a full step by step article. You'll need the steps for "website" and "database".

**Comment by bnjbvr** [comment]
Install SASS: `gem install sass --user-install`

Use SASS: `cd website/overfiew && sass --update ./sass:./css -f`

The only difference I spotted was the following:

```
-    header .rightSide>div {
+    header .rightSide div {
```

where `-` is the actual page, `+` what's generated by SASS. Could we fix this as part of this MR too, please?

**Comment by Timvde** [comment]
`sass` generates many other changes for me, but it's mostly capitalization and `#FFFFFF` instead of `white`. I ignored them.

I added the CSS changes too instead of only the SCSS.

**Comment by bnjbvr** [comment]
Looks good, thanks! This is going in production the next time we update the web site.

**Pull request merged**
