### PR TITLE
Update ARES-6 to 1.0.1

### PR DESCRIPTION
**Pull request by Constellation**
This patch updates ARES-6 benchmark to version 1.0.1. It fixes miscalculation in average worst cases.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thank you for the merge request. Looks good. Can you change the version number in `/benchmarks/ares6/VERSION` too, please? And then I can merge right away.

**Comment by Constellation** [comment]
Nice catch! I'll update the patch...

**Comment by Constellation** [comment]
OK, I've just updated the PR :)

**Comment by bnjbvr** [comment]
Thanks! This should go live in the next hours.

**Comment by Constellation** [comment]
Thank you :D

**Pull request merged**
