### PR TITLE
add web tooling benchmark

### PR DESCRIPTION
**Pull request by tebbi**
This adds the [Web Tooling Benchmark](https://github.com/v8/web-tooling-benchmark). The cli.js file is packed using `npm install`.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thanks for the pull request! Will have a look at it and then discuss it with our team for approval.

**Comment by bnjbvr** [comment]
Great, works like a charm! We'll run it on v8 only first, and will schedule it once a day. Hope that works for you! Thanks for the PR.

**Comment by tebbi** [comment]
Thanks a lot! There is just one issue I don't know how to fix: The unit in the graphs is ms instead of runs/sec and it doesn't follow the higher-is-better convention on AWFY to mirror the graph.

**Comment by bnjbvr** [comment]
Sure, that's a test suite setting that must be set in the database: the `better_direction` field in the web tooling benchmark entry in the `awfy_suite` had to be changed from `-1` to `1`. Hopefully, one day this will be in a simpler configuration file, or even in the Python code directly, so it's easier to manage. The updated graphs should show up in the next 10 minutes. Thanks for your feedback!

**Comment by bmeurer** [comment]
Looks better, thanks a lot 👍

**Comment by tebbi** [comment]
The graphs seem to be unchanged, that is, still the wrong way around. I guess something went wrong.

**Comment by bnjbvr** [comment]
I've cleared the JSON caches, let's see if the next processing (should happen in the next 15 minutes) does the right thing (in the meanwhile, the benchmark numbers might be unavailable).

**Comment by bnjbvr** [comment]
It's already been processed and I think the right order shows up now. @tebbi, is that correct?

**Comment by tebbi** [comment]
Yes, perfect! Thank you!

**Comment by Constellation** [comment]
That's nice :D Can I help to run it for JavaScriptCore?

**Comment by bnjbvr** [comment]
> That's nice :D Can I help to run it for JavaScriptCore?

Happy to have JSC run this benchmark too, whenever you and the JSC team feel it's a good time.

**Pull request merged**
