### PR TITLE
Allow arai on tryserver

### PR DESCRIPTION
**Pull request by arai-a**
I want to use awfy machines to test performance improvement/regression for WIP patches :)

### CODE REVIEW

**Comment by h4writer** [comment]
Seems like there is an error here. It should be "$split" instead of "split" in the second part. Can you also fix that for mine (hv1989) while you are here. Thanks!

**Comment by bnjbvr** [comment]
Looks good, thanks Arai! I'll merge once the `$` issue has been addressed.

**Comment by arai-a** [comment]
Thank you fore checking :)
fixed the error.

**Comment by bnjbvr** [comment]
Thank you, and welcome!

**Comment by arai-a** [comment]
I get the following error when I visit https://arewefastyet.com/schedule.php .

```
You must be logged in to visit this page.
```

I'm logging in as `arai.unmht@gmail.com` on Google (the top-right corner says "Signed in").
am I missing something?

**Comment by h4writer** [comment]
Interestingly I'm getting that too.
@bnjbvr: did this get merged automatically on the server or do we need to request a manual merge?

**Comment by bnjbvr** [comment]
Oops, yes, I still need to manually sync the server. I've just done it, can you please check? Thanks!

**Comment by arai-a** [comment]
yes, now I see "Schedule a Task" page.
Thank you!

**Pull request merged**
